import json
import re
import sqlite3

# Verified list of 82 products with 100% accurate titles and subcategories matching every photo
PRODUCTS_DATA = [
    # 1. Gold Koltuk (Page 1)
    {"id": 1, "title": "Gold Lüks Koltuk Takımı", "category": "living", "subcategory": "sofas", "productType": "Set", "price": 45000, "originalPrice": 52000, "image": "assets/minegolden_p1_2.webp", "gallery": ["assets/minegolden_p1_2.webp", "assets/minegolden_p1_1.webp", "assets/minegolden_p1_3.webp", "assets/minegolden_p1_4.webp", "assets/minegolden_p1_5.webp", "assets/minegolden_p1_6.webp"], "badges": ["İNEGÖL KOLEKSİYONU", "%100 MASİF", "ÜCRETSİZ MONTAJ"], "material": "İnegöl Masif Gürgen & Gold Paslanmaz Metal", "desc": "Antrasit kadife kumaşı, fırınlanmış gürgen iskeleti ve gold metal ayak detaylarıyla salonunuza lüks atmosfer katar."},
    {"id": 2, "title": "Gold 3'lü Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 23500, "originalPrice": 27000, "image": "assets/minegolden_p1_1.webp", "gallery": ["assets/minegolden_p1_1.webp", "assets/minegolden_p1_2.webp", "assets/minegolden_p1_5.webp", "assets/minegolden_p1_6.webp"], "badges": ["TEKİL PARÇA"], "material": "Fırınlanmış Gürgen İskelet & 32 DNS Sünger", "desc": "Geniş oturum alanı ve konforlu sırt minderi ile salonunuza zarafet katan 3'lü koltuk."},
    {"id": 3, "title": "Gold 2'li Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 18500, "originalPrice": 21000, "image": "assets/minegolden_p1_3.webp", "gallery": ["assets/minegolden_p1_3.webp", "assets/minegolden_p1_2.webp", "assets/minegolden_p1_5.webp"], "badges": ["TEKİL PARÇA"], "material": "Gürgen İskelet & Lüks Kumaş", "desc": "Kompakt ölçüleri ve şık gold detaylarıyla modern yaşam alanları için ideal 2'li koltuk."},
    {"id": 4, "title": "Gold Tekli Berjer", "category": "living", "subcategory": "armchairs", "productType": "Solo", "price": 11500, "originalPrice": 13500, "image": "assets/minegolden_p1_4.webp", "gallery": ["assets/minegolden_p1_4.webp", "assets/minegolden_p1_2.webp", "assets/minegolden_p1_1.webp"], "badges": ["ÖZEL RENK BERJER"], "material": "Masif Ahşap İskelet & Gold Metal Ayak", "desc": "Pembe kadife kumaşı ve zarif altın metal ayaklarıyla özel dinlenme berjeridir."},

    # 2. Zümrüt Avangarde Koltuk (Page 2)
    {"id": 5, "title": "Zümrüt Avangarde Koltuk Takımı", "category": "living", "subcategory": "sofas", "productType": "Set", "price": 48000, "originalPrice": 56000, "image": "assets/minegolden_p2_1.webp", "gallery": ["assets/minegolden_p2_1.webp", "assets/minegolden_p2_2.webp", "assets/minegolden_p2_3.webp", "assets/pieces/zumrut_berjer.webp", "assets/minegolden_p2_5.webp", "assets/minegolden_p2_6.webp"], "badges": ["KAPİTONE İŞÇİLİK", "LÜKS KADİFE"], "material": "El İşçiliği Kapitone & Fırınlanmış Kayın Ağacı", "desc": "Kapitone detayları, yumuşak kadife kumaşı ve kırlentleriyle salonunuza saray zarafeti getirir."},
    {"id": 6, "title": "Zümrüt 3'lü Kapitone Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 24500, "originalPrice": 28500, "image": "assets/minegolden_p2_2.webp", "gallery": ["assets/minegolden_p2_2.webp", "assets/minegolden_p2_1.webp", "assets/minegolden_p2_5.webp"], "badges": ["KAPİTONE İŞÇİLİK"], "material": "Gürgen Ağacı & 35 DNS HR Sünger", "desc": "El işçiliği sırt kapitone detaylarıyla klasik ve avangarde zarafeti buluşturan 3'lü koltuk."},
    {"id": 7, "title": "Zümrüt 2'li Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 19500, "originalPrice": 22500, "image": "assets/minegolden_p2_3.webp", "gallery": ["assets/minegolden_p2_3.webp", "assets/minegolden_p2_1.webp", "assets/minegolden_p2_6.webp"], "badges": ["TEKİL PARÇA"], "material": "Gürgen İskelet & İthal Kadife Kumaş", "desc": "Konforlu oturum ve şık kapitone sırt tasarımıyla 2'li koltuk."},
    {"id": 8, "title": "Zümrüt Tekli Berjer", "category": "living", "subcategory": "armchairs", "productType": "Solo", "price": 11500, "originalPrice": 13500, "image": "assets/pieces/zumrut_berjer.webp", "gallery": ["assets/pieces/zumrut_berjer.webp", "assets/minegolden_p2_1.webp", "assets/minegolden_p2_4.webp"], "badges": ["ÖZEL BERJER"], "material": "Masif Kayın Ayak & Ergonomik Döşeme", "desc": "Ergonomik oturum minderi ve şık kol yapısıyla salonunuza eşsiz zarafet katan berjer."},

    # 3. Bohem Natural Keten Koltuk (Page 3)
    {"id": 9, "title": "Bohem Natural Keten Koltuk Takımı", "category": "living", "subcategory": "sofas", "productType": "Set", "price": 42000, "originalPrice": 49000, "image": "assets/minegolden_p3_2.webp", "gallery": ["assets/minegolden_p3_2.webp", "assets/minegolden_p3_1.webp", "assets/pieces/bohem_berjer.webp", "assets/pieces/bohem_puf.webp", "assets/minegolden_p3_5.webp", "assets/minegolden_p3_6.webp"], "badges": ["DOĞAL KETEN", "%100 ORGANİK"], "material": "Doğal Dokuma Keten & Masif Meşe İskelet", "desc": "Nefes alabilen doğal keten kumaşı ve ahşap ayak detaylarıyla ferah yaşam alanları sunar."},
    {"id": 10, "title": "Bohem 3'lü Natural Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 22000, "originalPrice": 25000, "image": "assets/minegolden_p3_1.webp", "gallery": ["assets/minegolden_p3_1.webp", "assets/minegolden_p3_2.webp", "assets/minegolden_p3_5.webp"], "badges": ["ORGANİK DOKU"], "material": "Masif Meşe İskelet & Doğal Keten Kumaş", "desc": "Ferah ve minimalist tasarımıyla konfor sunan geniş 3'lü keten koltuk."},
    {"id": 11, "title": "Bohem Tekli Koltuk / Berjer", "category": "living", "subcategory": "armchairs", "productType": "Solo", "price": 11000, "originalPrice": 13000, "image": "assets/pieces/bohem_berjer.webp", "gallery": ["assets/pieces/bohem_berjer.webp", "assets/minegolden_p3_2.webp", "assets/minegolden_p3_3.webp"], "badges": ["DOĞAL AHŞAP"], "material": "Doğal Keten & Masif Ahşap Ayak", "desc": "Minimalist formuyla her köşeye uyum sağlayan rahat tekli koltuk."},
    {"id": 12, "title": "Bohem Natural Yuvarlak Orta Sehpa & Puf", "category": "living", "subcategory": "tables", "productType": "Solo", "price": 7500, "originalPrice": 9000, "image": "assets/pieces/bohem_puf.webp", "gallery": ["assets/pieces/bohem_puf.webp", "assets/minegolden_p3_2.webp", "assets/minegolden_p3_4.webp"], "badges": ["FONKSİYONEL SEHPA"], "material": "Doğal Keten & Masif Ahşap Gövde", "desc": "Hem ayak uzatma pufu hem de yuvarlak orta sehpa olarak kullanılan çok amaçlı modül."},

    # 4. Mono Modern Bukle Koltuk (Page 4)
    {"id": 13, "title": "Mono Modern Koltuk Takımı", "category": "living", "subcategory": "sofas", "productType": "Set", "price": 44000, "originalPrice": 51000, "image": "assets/minegolden_p4_1.webp", "gallery": ["assets/minegolden_p4_1.webp", "assets/minegolden_p4_2.webp", "assets/pieces/mono_2li.webp", "assets/minegolden_p4_3.webp", "assets/minegolden_p4_5.webp", "assets/minegolden_p4_6.webp"], "badges": ["BUKLE KUMAŞ", "MODERN TREND"], "material": "Teddy Bukle Kumaş & Fırınlanmış Gürgen Ağacı", "desc": "Dokulu bukle kumaşı ve yuvarlak hatlarıyla modern evlerin gözdesi."},
    {"id": 14, "title": "Mono 3'lü Bukle Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 22000, "originalPrice": 25500, "image": "assets/minegolden_p4_2.webp", "gallery": ["assets/minegolden_p4_2.webp", "assets/minegolden_p4_1.webp", "assets/minegolden_p4_5.webp"], "badges": ["BUKLE DOKU"], "material": "Bukle Kumaş & 35 DNS Hyper Sünger", "desc": "Trend bukle dokusu ve geniş oturumu ile salonunuzun odak noktası."},
    {"id": 15, "title": "Mono 2'li Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 17000, "originalPrice": 19500, "image": "assets/pieces/mono_2li.webp", "gallery": ["assets/pieces/mono_2li.webp", "assets/minegolden_p4_1.webp", "assets/minegolden_p4_4.webp"], "badges": ["KOMPAKT ÖLÇÜ"], "material": "Gürgen İskelet & Yumuşak Bukle Kumaş", "desc": "Kompakt salonlar için konfor sunan 2'li koltuk."},
    {"id": 16, "title": "Mono Tekli Berjer", "category": "living", "subcategory": "armchairs", "productType": "Solo", "price": 11500, "originalPrice": 13500, "image": "assets/minegolden_p4_3.webp", "gallery": ["assets/minegolden_p4_3.webp", "assets/minegolden_p4_1.webp", "assets/minegolden_p4_6.webp"], "badges": ["DİZAYN BERJER"], "material": "Bukle Kumaş & Masif Ayaklar", "desc": "Kavisli arkalığı ve yumuşak minderiyle okuma köşelerinin vazgeçilmezi."},

    # 5. Leon Ahşap Ayaklı Koltuk (Page 5)
    {"id": 17, "title": "Leon Ahşap Ayaklı Koltuk Takımı", "category": "living", "subcategory": "sofas", "productType": "Set", "price": 46000, "originalPrice": 53000, "image": "assets/minegolden_p5_1.webp", "gallery": ["assets/minegolden_p5_1.webp", "assets/minegolden_p5_2.webp", "assets/minegolden_p5_3.webp", "assets/pieces/leon_berjer.webp", "assets/minegolden_p5_5.webp", "assets/minegolden_p5_6.webp"], "badges": ["MASİF AHŞAP", "İNEGÖL İMZASI"], "material": "Fırınlanmış Masif Ceviz Ayaklar & İthal Kumaş", "desc": "Masif ceviz ayak yapısı ve ergonomik oturum desteğiyle modern salonların vazgeçilmezi."},
    {"id": 18, "title": "Leon Ahşap 3'lü Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 23000, "originalPrice": 26500, "image": "assets/minegolden_p5_2.webp", "gallery": ["assets/minegolden_p5_2.webp", "assets/minegolden_p5_1.webp", "assets/minegolden_p5_5.webp"], "badges": ["MASİF DETAY"], "material": "Masif Gürgen Gövde & Ceviz Ahşap Ayak", "desc": "Sağlam ahşap iskeleti ve kaliteli dokuma kumaşıyla uzun yıllar konfor sunar."},
    {"id": 19, "title": "Leon Ahşap 2'li Koltuk", "category": "living", "subcategory": "sofas", "productType": "Solo", "price": 18000, "originalPrice": 20500, "image": "assets/minegolden_p5_3.webp", "gallery": ["assets/minegolden_p5_3.webp", "assets/minegolden_p5_1.webp", "assets/minegolden_p5_6.webp"], "badges": ["TEKİL PARÇA"], "material": "Fırınlanmış Ahşap & İthal Kumaş", "desc": "Şık ceviz ayakları ve konforlu minder yapısıyla 2'li koltuk."},
    {"id": 20, "title": "Leon Tekli Ahşap Berjer", "category": "living", "subcategory": "armchairs", "productType": "Solo", "price": 11500, "originalPrice": 13500, "image": "assets/pieces/leon_berjer.webp", "gallery": ["assets/pieces/leon_berjer.webp", "assets/minegolden_p5_1.webp", "assets/minegolden_p5_4.webp"], "badges": ["MASİF BERJER"], "material": "Masif Ceviz Ayak & Ortopedik Oturum", "desc": "Ahşap kavisli ayakları ve rahat oturumu ile özel dinlenme koltuğu."},

    # 6. TV Üniteleri (Page 19 & 20)
    {"id": 21, "title": "Sahra Modern TV & Duvar Ünitesi", "category": "living", "subcategory": "consoles", "productType": "Set", "price": 28000, "originalPrice": 33000, "image": "assets/minegolden_p19_1.webp", "gallery": ["assets/minegolden_p19_1.webp", "assets/minegolden_p19_2.webp", "assets/minegolden_p19_3.webp", "assets/minegolden_p19_4.webp", "assets/minegolden_p19_5.webp"], "badges": ["LED AYDINLATMALI", "FRENLİ SİSTEM"], "material": "E1 Doğal Meşe Kaplama & MDF Gövde", "desc": "Alt konsol, üst asma dolap ve LED aydınlatmalı duvar paneli ile komple TV yaşam ünitesi."},
    {"id": 22, "title": "Sahra TV Alt Blok Konsol", "category": "living", "subcategory": "consoles", "productType": "Solo", "price": 16500, "originalPrice": 19500, "image": "assets/minegolden_p19_2.webp", "gallery": ["assets/minegolden_p19_2.webp", "assets/minegolden_p19_1.webp", "assets/minegolden_p19_4.webp"], "badges": ["GİZLİ KABLO KANALI"], "material": "Doğal Meşe MDF Gövde & Frenli Ray", "desc": "Geniş çekmeceleri ve şık ahşap dokusuyla TV alt sehpası."},
    {"id": 23, "title": "Sahra Asma Duvar Rafı & Üst Dolap", "category": "living", "subcategory": "consoles", "productType": "Solo", "price": 12500, "originalPrice": 14500, "image": "assets/minegolden_p19_3.webp", "gallery": ["assets/minegolden_p19_3.webp", "assets/minegolden_p19_1.webp", "assets/minegolden_p19_5.webp"], "badges": ["ASMA MODÜL"], "material": "MDF & LED Gizli Aydınlatma", "desc": "Dekoratif objeler ve kitaplar için modern asma duvar ünitesi."},
    {"id": 24, "title": "Salvador Lüks TV & Yaşam Ünitesi", "category": "living", "subcategory": "consoles", "productType": "Set", "price": 29500, "originalPrice": 35000, "image": "assets/minegolden_p20_5.webp", "gallery": ["assets/minegolden_p20_5.webp", "assets/minegolden_p20_1.webp", "assets/minegolden_p20_3.webp", "assets/minegolden_p20_2.webp", "assets/minegolden_p20_4.webp"], "badges": ["LÜKS KAPLAMA", "ÖZEL MEKANİZMA"], "material": "Lüks Kaplama & Metal Detaylar", "desc": "Göz alıcı ahşap paneli ve geniş depolama alanıyla lüks TV ünitesi."},
    {"id": 25, "title": "Salvador TV Alt Konsol", "category": "living", "subcategory": "consoles", "productType": "Solo", "price": 17500, "originalPrice": 20500, "image": "assets/minegolden_p20_1.webp", "gallery": ["assets/minegolden_p20_1.webp", "assets/minegolden_p20_5.webp", "assets/minegolden_p20_2.webp"], "badges": ["FRENLİ ÇEKMECE"], "material": "MDF Gövde & Metal Ayaklar", "desc": "Şık alt TV sehpası ve depolama modülü."},
    {"id": 26, "title": "Salvador Ahşap 3'lü Orta & Yan Sehpa Seti", "category": "living", "subcategory": "tables", "productType": "Solo", "price": 13000, "originalPrice": 15500, "image": "assets/minegolden_p20_3.webp", "gallery": ["assets/minegolden_p20_3.webp", "assets/minegolden_p20_5.webp", "assets/minegolden_p20_4.webp"], "badges": ["3'LÜ SEHPA SETİ"], "material": "Doğal Ahşap Masif Kaplama", "desc": "Farklı boylarda 3 adet yuvarlak masif ahşap orta ve yan sehpa takımı."},

    # 7. Yemek Odaları (Page 6, 7, 8, 9, 10)
    {"id": 27, "title": "İcon Yuvarlak Masa Sandalye Takımı", "category": "dining", "subcategory": "dining-tables", "productType": "Set", "price": 34000, "originalPrice": 39500, "image": "assets/minegolden_p7_1.webp", "gallery": ["assets/minegolden_p7_1.webp", "assets/minegolden_p7_2.webp", "assets/minegolden_p7_3.webp", "assets/minegolden_p7_4.webp", "assets/minegolden_p7_5.webp"], "badges": ["YUVARLAK MASA", "MASİF AYAK"], "material": "Masif Meşe Ayak & Doğal Kaplama", "desc": "Samimi yemek sohbetleri için yuvarlak masa ve 4 adet ergonomik sandalye seti."},
    {"id": 28, "title": "İcon Yuvarlak Yemek Masası", "category": "dining", "subcategory": "dining-tables", "productType": "Solo", "price": 18500, "originalPrice": 21500, "image": "assets/minegolden_p7_2.webp", "gallery": ["assets/minegolden_p7_2.webp", "assets/minegolden_p7_1.webp", "assets/minegolden_p7_5.webp"], "badges": ["DOĞAL MEŞE"], "material": "Masif Ahşap Ayaklar & Dayanıklı Tabla", "desc": "120 cm çapında doğal ahşap yuvarlak yemek masası."},
    {"id": 29, "title": "İcon Ergonomik Sandalye (4 Adet)", "category": "dining", "subcategory": "chairs", "productType": "Solo", "price": 16500, "originalPrice": 19000, "image": "assets/minegolden_p7_3.webp", "gallery": ["assets/minegolden_p7_3.webp", "assets/minegolden_p7_1.webp"], "badges": ["4'LÜ SET"], "material": "Masif Ahşap Ayak & Silinebilir Kumaş", "desc": "Ergonomik sırt yapısı ve yumuşak oturumuyla 4 adet yemek sandalyesi."},

    {"id": 30, "title": "İcon Meşe Ahşap Yemek Odası Takımı", "category": "dining", "subcategory": "dining-tables", "productType": "Set", "price": 49000, "originalPrice": 58000, "image": "assets/minegolden_p8_1.webp", "gallery": ["assets/minegolden_p8_1.webp", "assets/minegolden_p8_2.webp", "assets/minegolden_p8_3.webp", "assets/minegolden_p8_4.webp", "assets/minegolden_p8_5.webp"], "badges": ["AÇILIR MASA", "KONSOL DAHİL"], "material": "Masif Meşe Ağacı & Lüks Konsol Aynası", "desc": "Açılır yemek masası, 6 adet sandalye ve aynalı konsoluyla eksiksiz yemek odası takımı."},
    {"id": 31, "title": "İcon Meşe Yemek Masası", "category": "dining", "subcategory": "dining-tables", "productType": "Solo", "price": 21000, "originalPrice": 24500, "image": "assets/minegolden_p8_2.webp", "gallery": ["assets/minegolden_p8_2.webp", "assets/minegolden_p8_1.webp", "assets/minegolden_p8_5.webp"], "badges": ["AÇILIR FONKSİYON"], "material": "Masif Meşe Gövde", "desc": "Ortadan açılır mekanizmasıyla 6-8 kişilik geniş yemek masası."},
    {"id": 32, "title": "İcon Meşe Sandalye (6 Adet)", "category": "dining", "subcategory": "chairs", "productType": "Solo", "price": 18000, "originalPrice": 21000, "image": "assets/minegolden_p8_3.webp", "gallery": ["assets/minegolden_p8_3.webp", "assets/minegolden_p8_1.webp"], "badges": ["6'LI SET"], "material": "Masif Ağaç & Leke Tutmaz Kumaş", "desc": "Şık dikiş detayları ve konforlu oturumuyla 6 adet sandalye seti."},
    {"id": 33, "title": "İcon Aynalı Ahşap Konsol & Büfe", "category": "dining", "subcategory": "buffets", "productType": "Solo", "price": 19500, "originalPrice": 23000, "image": "assets/minegolden_p8_4.webp", "gallery": ["assets/minegolden_p8_4.webp", "assets/minegolden_p8_1.webp", "assets/minegolden_p8_5.webp"], "badges": ["AYNA DAHİL"], "material": "Doğal Meşe MDF & Frenli Kapaklar", "desc": "Geniş iç hacmi ve şık aynasıyla yemek odası konsolu."},

    {"id": 34, "title": "Forte Meşe Modern Yemek Odası Takımı", "category": "dining", "subcategory": "dining-tables", "productType": "Set", "price": 52000, "originalPrice": 61000, "image": "assets/minegolden_p9_1.webp", "gallery": ["assets/minegolden_p9_1.webp", "assets/minegolden_p9_2.webp", "assets/minegolden_p9_3.webp", "assets/minegolden_p9_4.webp", "assets/minegolden_p9_5.webp", "assets/minegolden_p9_6.webp"], "badges": ["ÇAPRAZ AYAK", "MODERN TASARIM"], "material": "Fırınlanmış Masif Ağaç & Çapraz Ayaklar", "desc": "Çapraz metal ayaklı yemek masası, 6 adet tasarım sandalye ve konsol takımı."},
    {"id": 35, "title": "Forte Meşe Çapraz Ayak Masa", "category": "dining", "subcategory": "dining-tables", "productType": "Solo", "price": 23500, "originalPrice": 27500, "image": "assets/minegolden_p9_3.webp", "gallery": ["assets/minegolden_p9_3.webp", "assets/minegolden_p9_1.webp", "assets/minegolden_p9_6.webp"], "badges": ["ÖZEL AYAK"], "material": "Masif Meşe Tabla & Elektrostatik Metal Ayak", "desc": "Endüstriyel ve modern dokuyu buluşturan şık yemek masası."},
    {"id": 36, "title": "Forte Kumaş Sandalye (6 Adet)", "category": "dining", "subcategory": "chairs", "productType": "Solo", "price": 19000, "originalPrice": 22000, "image": "assets/minegolden_p9_4.webp", "gallery": ["assets/minegolden_p9_4.webp", "assets/minegolden_p9_1.webp", "assets/minegolden_p9_5.webp"], "badges": ["6'LI SET"], "material": "Metal İskelet & Nubuk Kumaş", "desc": "Yüksek sırt konforu sunan 6 adet modern yemek sandalyesi."},
    {"id": 37, "title": "Forte Aynalı Konsol & Büfe", "category": "dining", "subcategory": "buffets", "productType": "Solo", "price": 21000, "originalPrice": 24500, "image": "assets/minegolden_p9_2.webp", "gallery": ["assets/minegolden_p9_2.webp", "assets/minegolden_p9_1.webp"], "badges": ["LÜKS BÜFE"], "material": "MDF Gövde & Aynalı Ön Kapaklar", "desc": "Geniş iç rafları ve amortisörlü kapak sistemiyle şık büfe."},

    {"id": 38, "title": "Seramik Mutfak & Yemek Masası Takımı", "category": "dining", "subcategory": "dining-tables", "productType": "Set", "price": 31000, "originalPrice": 36000, "image": "assets/minegolden_p6_1.webp", "gallery": ["assets/minegolden_p6_1.webp", "assets/minegolden_p6_2.webp", "assets/minegolden_p6_3.webp", "assets/minegolden_p6_4.webp"], "badges": ["ÇİZİLMEZ SERAMİK", "ISIYA DAYANIKLI"], "material": "Porselen Seramik Üst Tabla & Metal Ayak", "desc": "Çizilmez, leke tutmaz seramik masa ve 4 adet sandalye seti."},
    {"id": 39, "title": "Seramik Mutfak & Yemek Masası", "category": "dining", "subcategory": "dining-tables", "productType": "Solo", "price": 17500, "originalPrice": 20500, "image": "assets/minegolden_p6_2.webp", "gallery": ["assets/minegolden_p6_2.webp", "assets/minegolden_p6_1.webp", "assets/minegolden_p6_4.webp"], "badges": ["PORSELEN YÜZEY"], "material": "Porselen Seramik Tabla", "desc": "Günlük mutfak ve salon kullanımı için dayanıklı seramik masa."},
    {"id": 40, "title": "Seramik Takım Sandalyesi (4 Adet)", "category": "dining", "subcategory": "chairs", "productType": "Solo", "price": 14500, "originalPrice": 17000, "image": "assets/minegolden_p6_3.webp", "gallery": ["assets/minegolden_p6_3.webp", "assets/minegolden_p6_1.webp"], "badges": ["KOLAY TEMİZLENİR"], "material": "Metal Ayak & Su İtici Kumaş", "desc": "Leke tutmaz kumaşı ve dayanıklı metal ayaklarıyla 4 adet sandalye."},

    {"id": 41, "title": "İpek Lüks Yemek Odası Takımı", "category": "dining", "subcategory": "dining-tables", "productType": "Set", "price": 56000, "originalPrice": 65000, "image": "assets/minegolden_p10_1.webp", "gallery": ["assets/minegolden_p10_1.webp", "assets/minegolden_p10_2.webp", "assets/minegolden_p10_3.webp", "assets/minegolden_p10_4.webp", "assets/minegolden_p10_5.webp", "assets/minegolden_p10_6.webp"], "badges": ["LÜKS SERİ", "GOLD DETAYLI"], "material": "Aynalı Konsol & Açılır Masa", "desc": "Açılır masa, 6 adet sandalye ve aynalı büfesiyle yemek odası takımı."},
    {"id": 42, "title": "İpek Aynalı Konsol & Büfe", "category": "dining", "subcategory": "buffets", "productType": "Solo", "price": 22500, "originalPrice": 26500, "image": "assets/minegolden_p10_2.webp", "gallery": ["assets/minegolden_p10_2.webp", "assets/minegolden_p10_1.webp", "assets/minegolden_p10_6.webp"], "badges": ["AYNA DAHİL"], "material": "MDF & Füme Ayna Detaylar", "desc": "Geniş iç çekmeceleri ve lüks kulplarıyla göz alıcı konsol."},
    {"id": 43, "title": "İpek Açılır Fonksiyonel Masa", "category": "dining", "subcategory": "dining-tables", "productType": "Solo", "price": 23000, "originalPrice": 27000, "image": "assets/minegolden_p10_3.webp", "gallery": ["assets/minegolden_p10_3.webp", "assets/minegolden_p10_1.webp", "assets/minegolden_p10_5.webp"], "badges": ["AÇILIR MASA"], "material": "Doğal Kaplama & Gizli Mekanizma", "desc": "Kolay açılan teleskopik mekanizmalı lüks yemek masası."},
    {"id": 44, "title": "İpek Lüks Sandalye (6 Adet)", "category": "dining", "subcategory": "chairs", "productType": "Solo", "price": 19500, "originalPrice": 23000, "image": "assets/minegolden_p10_4.webp", "gallery": ["assets/minegolden_p10_4.webp", "assets/minegolden_p10_1.webp"], "badges": ["6'LI SET"], "material": "Kadife Kumaş & Masif Ayaklar", "desc": "Altın detaylı ayakları ve kapitone sırt dikişleriyle 6 adet sandalye."},

    # 8. Yatak Odaları (Page 11-18)
    {"id": 45, "title": "Zen Modern Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 54000, "originalPrice": 63000, "image": "assets/minegolden_p11_5.webp", "gallery": ["assets/minegolden_p11_5.webp", "assets/minegolden_p11_4.webp", "assets/minegolden_p11_6.webp", "assets/minegolden_p11_2.webp", "assets/minegolden_p11_3.webp", "assets/minegolden_p11_1.webp"], "badges": ["6 KAPAKLI GARDROP", "BAZALI KARYOLA"], "material": "MDF Gövde & Doğal Meşe Kaplama", "desc": "6 kapaklı gardırop, LED aydınlatmalı karyola, şifonyer ve 2 adet komodin seti."},
    {"id": 46, "title": "Zen 6 Kapaklı Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 26000, "originalPrice": 30500, "image": "assets/minegolden_p11_4.webp", "gallery": ["assets/minegolden_p11_4.webp", "assets/minegolden_p11_5.webp", "assets/minegolden_p11_1.webp"], "badges": ["GENİŞ İÇ HACİM"], "material": "MDF Gövde & Frenli Menteşeler", "desc": "Askılıklar, pantolonluk ve çekmeceleriyle 6 kapaklı gardırop."},
    {"id": 47, "title": "Zen Karyola & Yatak Başlığı", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 19500, "originalPrice": 23000, "image": "assets/minegolden_p11_6.webp", "gallery": ["assets/minegolden_p11_6.webp", "assets/minegolden_p11_5.webp", "assets/minegolden_p11_3.webp"], "badges": ["160x200 BAZALI"], "material": "Kumaş Kaplı Başlık & Çelik Baza", "desc": "Geniş sandıklı bazası ve LED ışıklı yatak başlığı."},
    {"id": 48, "title": "Zen Aynalı Şifonyer & Makyaj Masası", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 14500, "originalPrice": 17000, "image": "assets/minegolden_p11_2.webp", "gallery": ["assets/minegolden_p11_2.webp", "assets/minegolden_p11_5.webp", "assets/minegolden_p11_1.webp"], "badges": ["AYNA DAHİL"], "material": "MDF Gövde & Özel Kesim Ayna", "desc": "Mücevher çekmeceli ve geniş saklama alanlı aynalı şifonyer."},
    {"id": 49, "title": "Zen Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 8500, "originalPrice": 10000, "image": "assets/minegolden_p11_3.webp", "gallery": ["assets/minegolden_p11_3.webp", "assets/minegolden_p11_5.webp", "assets/minegolden_p11_6.webp"], "badges": ["2'Lİ SET"], "material": "MDF & Frenli Çekmece", "desc": "Yatak başı için 2 adet şık ahşap komodin."},

    {"id": 50, "title": "Dora Ahşap Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 52000, "originalPrice": 61000, "image": "assets/minegolden_p12_1.webp", "gallery": ["assets/minegolden_p12_1.webp", "assets/minegolden_p12_2.webp", "assets/minegolden_p12_4.webp", "assets/minegolden_p12_3.webp", "assets/minegolden_p12_5.webp", "assets/minegolden_p12_6.webp"], "badges": ["DOĞAL AHŞAP"], "material": "Masif Meşe Kaplama & MDF Gövde", "desc": "Gardırop, başlıklı karyola, aynalı şifonyer ve 2 adet komodin seti."},
    {"id": 51, "title": "Dora 6 Kapaklı Ahşap Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 25000, "originalPrice": 29000, "image": "assets/minegolden_p12_2.webp", "gallery": ["assets/minegolden_p12_2.webp", "assets/minegolden_p12_1.webp", "assets/minegolden_p12_6.webp"], "badges": ["FRENLİ KAPAK"], "material": "Doğal Meşe MDF Gövde", "desc": "Geniş depolama rafları ve askılık alanlarıyla 6 kapaklı gardırop."},
    {"id": 52, "title": "Dora Karyola (Başlıklı)", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 18500, "originalPrice": 22000, "image": "assets/minegolden_p12_4.webp", "gallery": ["assets/minegolden_p12_4.webp", "assets/minegolden_p12_1.webp", "assets/minegolden_p12_5.webp"], "badges": ["160x200"], "material": "Masif Ahşap Karyola İskeleti", "desc": "Açılır sandıklı bazası ve konforlu ahşap başlığıyla karyola."},
    {"id": 53, "title": "Dora Şifonyer & Ayna", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 13500, "originalPrice": 16000, "image": "assets/minegolden_p12_3.webp", "gallery": ["assets/minegolden_p12_3.webp", "assets/minegolden_p12_1.webp", "assets/minegolden_p12_6.webp"], "badges": ["AYNA DAHİL"], "material": "MDF & Masif Ahşap Ayak", "desc": "Fonksiyonel çekmeceli şifonyer ve yuvarlak ahşap ayna."},
    {"id": 54, "title": "Dora Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 8000, "originalPrice": 9500, "image": "assets/minegolden_p12_5.webp", "gallery": ["assets/minegolden_p12_5.webp", "assets/minegolden_p12_1.webp", "assets/minegolden_p12_4.webp"], "badges": ["2'Lİ SET"], "material": "MDF & Frenli Ray", "desc": "2 adet ahşap yatak başı komodini."},

    {"id": 55, "title": "Elegance Lüks Cam Kapaklı Yatak Odası", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 59000, "originalPrice": 69000, "image": "assets/minegolden_p13_1.webp", "gallery": ["assets/minegolden_p13_1.webp", "assets/minegolden_p13_2.webp", "assets/minegolden_p13_4.webp", "assets/minegolden_p13_6.webp", "assets/minegolden_p13_5.webp", "assets/minegolden_p13_3.webp"], "badges": ["FÜME CAMLI", "İÇ AYDINLATMA"], "material": "Füme Temperli Cam & Alüminyum Profil", "desc": "LED aydınlatmalı cam kapaklı gardırop, lüks karyola, makyaj masası ve komodin takımı."},
    {"id": 56, "title": "Elegance Füme Cam Kapaklı Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 29000, "originalPrice": 34000, "image": "assets/minegolden_p13_2.webp", "gallery": ["assets/minegolden_p13_2.webp", "assets/minegolden_p13_1.webp", "assets/minegolden_p13_3.webp"], "badges": ["LED AYDINLATMALI"], "material": "Temperli Füme Cam & Siyah Profil", "desc": "Giyinme odası konseptini evinize getiren lüks cam kapaklı gardırop."},
    {"id": 57, "title": "Elegance Karyola & Lüks Başlık", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 21000, "originalPrice": 24500, "image": "assets/minegolden_p13_4.webp", "gallery": ["assets/minegolden_p13_4.webp", "assets/minegolden_p13_1.webp", "assets/minegolden_p13_5.webp"], "badges": ["LÜKS DÖŞEME"], "material": "Kadife Döşeme Başlık & Baza", "desc": "Özel dikişli yüksek yatak başlığı ve sandıklı baza."},
    {"id": 58, "title": "Elegance Şifonyer & Makyaj Aynası", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 15500, "originalPrice": 18000, "image": "assets/minegolden_p13_6.webp", "gallery": ["assets/minegolden_p13_6.webp", "assets/minegolden_p13_1.webp", "assets/minegolden_p13_3.webp"], "badges": ["LEDLİ AYNA"], "material": "MDF & LED Makyaj Aynası", "desc": "Dokunmatik LED ışıklı aynasıyla şık makyaj masası."},
    {"id": 59, "title": "Elegance Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 9000, "originalPrice": 10500, "image": "assets/minegolden_p13_5.webp", "gallery": ["assets/minegolden_p13_5.webp", "assets/minegolden_p13_1.webp", "assets/minegolden_p13_4.webp"], "badges": ["2'Lİ SET"], "material": "Cam Üst Yüzey & MDF", "desc": "Cam üst tablalı 2 adet modern komodin."},

    {"id": 60, "title": "Luna Akrilik Modern Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 51000, "originalPrice": 60000, "image": "assets/minegolden_p14_1.webp", "gallery": ["assets/minegolden_p14_1.webp", "assets/minegolden_p14_2.webp", "assets/minegolden_p14_4.webp", "assets/minegolden_p14_6.webp", "assets/minegolden_p14_3.webp", "assets/minegolden_p14_5.webp"], "badges": ["PARLAK BEYAZ"], "material": "Parlak Beyaz Akrilik & MDF Gövde", "desc": "Ferah beyaz tasarımıyla 6 kapaklı gardırop, karyola, şifonyer ve komodin takımı."},
    {"id": 61, "title": "Luna 6 Kapaklı Beyaz Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 24500, "originalPrice": 28500, "image": "assets/minegolden_p14_2.webp", "gallery": ["assets/minegolden_p14_2.webp", "assets/minegolden_p14_1.webp", "assets/minegolden_p14_5.webp"], "badges": ["ÇİZİLMEZ AKRİLİK"], "material": "Parlak Akrilik Kapak", "desc": "Aydınlık yatak odaları için 6 kapaklı gardırop."},
    {"id": 62, "title": "Luna Karyola (Başlıklı)", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 18000, "originalPrice": 21000, "image": "assets/minegolden_p14_4.webp", "gallery": ["assets/minegolden_p14_4.webp", "assets/minegolden_p14_1.webp", "assets/minegolden_p14_3.webp"], "badges": ["BAZALI"], "material": "Beyaz Gövde & Kumaş Başlık", "desc": "Modern beyaz karyola ve baza."},
    {"id": 63, "title": "Luna Şifonyer", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 13000, "originalPrice": 15500, "image": "assets/minegolden_p14_6.webp", "gallery": ["assets/minegolden_p14_6.webp", "assets/minegolden_p14_1.webp", "assets/minegolden_p14_5.webp"], "badges": ["AYNA DAHİL"], "material": "Akrilik Yüzey & MDF", "desc": "Geniş çekmeceli beyaz şifonyer."},
    {"id": 64, "title": "Luna Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 7800, "originalPrice": 9200, "image": "assets/minegolden_p14_3.webp", "gallery": ["assets/minegolden_p14_3.webp", "assets/minegolden_p14_1.webp", "assets/minegolden_p14_4.webp"], "badges": ["2'Lİ SET"], "material": "Beyaz Akrilik & Raylı", "desc": "2 adet beyaz yatak başı komodini."},

    {"id": 65, "title": "Masal Krem & Gold Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 55000, "originalPrice": 64000, "image": "assets/minegolden_p15_1.webp", "gallery": ["assets/minegolden_p15_1.webp", "assets/minegolden_p15_3.webp", "assets/minegolden_p15_4.webp", "assets/minegolden_p15_5.webp", "assets/minegolden_p15_6.webp", "assets/minegolden_p15_2.webp"], "badges": ["KREM & GOLD"], "material": "Mat Krem MDF & Gold Metal Kulplar", "desc": "Zarif krem lake yüzeyi ve altın detaylarıyla komple yatak odası takımı."},
    {"id": 66, "title": "Masal 6 Kapaklı Krem Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 26500, "originalPrice": 31000, "image": "assets/minegolden_p15_3.webp", "gallery": ["assets/minegolden_p15_3.webp", "assets/minegolden_p15_1.webp", "assets/minegolden_p15_2.webp"], "badges": ["GOLD KULPLAR"], "material": "MDF Gövde & Lake Kapaklar", "desc": "Özel desenli kapakları ve geniş iç hacmiyle gardırop."},
    {"id": 67, "title": "Masal Karyola & Yatak Başlığı", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 19500, "originalPrice": 23000, "image": "assets/minegolden_p15_4.webp", "gallery": ["assets/minegolden_p15_4.webp", "assets/minegolden_p15_1.webp", "assets/minegolden_p15_6.webp"], "badges": ["KAPİTONE BAŞLIK"], "material": "Krem Kumaş & Baza", "desc": "Altın çerçeveli kapitone yatak başlığı ve baza."},
    {"id": 68, "title": "Masal Şifonyer & Aynası", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 14000, "originalPrice": 16500, "image": "assets/minegolden_p15_5.webp", "gallery": ["assets/minegolden_p15_5.webp", "assets/minegolden_p15_1.webp", "assets/minegolden_p15_2.webp"], "badges": ["AYNA DAHİL"], "material": "MDF Lake & Gold Ayna", "desc": "Gold çerçeveli aynasıyla lüks krem şifonyer."},
    {"id": 69, "title": "Masal Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 8200, "originalPrice": 9800, "image": "assets/minegolden_p15_6.webp", "gallery": ["assets/minegolden_p15_6.webp", "assets/minegolden_p15_1.webp", "assets/minegolden_p15_4.webp"], "badges": ["2'Lİ SET"], "material": "Lake Yüzey & Gold Kulp", "desc": "2 adet lüks krem komodin."},

    {"id": 70, "title": "Respiro Bohem Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 53000, "originalPrice": 62000, "image": "assets/minegolden_p16_1.webp", "gallery": ["assets/minegolden_p16_1.webp", "assets/minegolden_p16_3.webp", "assets/minegolden_p16_2.webp", "assets/minegolden_p16_4.webp", "assets/minegolden_p16_5.webp", "assets/minegolden_p16_6.webp"], "badges": ["MASİF DOĞAL"], "material": "Masif Meşe & Doğal Ahşap", "desc": "Doğal ahşap dokusu, masif karyolası ve geniş gardırobuyla huzurlu uyku alanı."},
    {"id": 71, "title": "Respiro Ahşap Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 25500, "originalPrice": 29500, "image": "assets/minegolden_p16_3.webp", "gallery": ["assets/minegolden_p16_3.webp", "assets/minegolden_p16_1.webp", "assets/minegolden_p16_6.webp"], "badges": ["DOĞAL MEŞE"], "material": "Masif Ahşap Kaplama", "desc": "Geniş iç hacmi ve şık ahşap kulplarıyla gardırop."},
    {"id": 72, "title": "Respiro Masif Ahşap Karyola", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 19000, "originalPrice": 22500, "image": "assets/minegolden_p16_2.webp", "gallery": ["assets/minegolden_p16_2.webp", "assets/minegolden_p16_1.webp", "assets/minegolden_p16_5.webp"], "badges": ["MASİF İSKELET"], "material": "Masif Meşe Ağacı", "desc": "Tamamen masif ahşaptan üretilmiş dayanıklı karyola."},
    {"id": 73, "title": "Respiro Şifonyer & Ayna", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 13500, "originalPrice": 16000, "image": "assets/minegolden_p16_4.webp", "gallery": ["assets/minegolden_p16_4.webp", "assets/minegolden_p16_1.webp", "assets/minegolden_p16_6.webp"], "badges": ["AYNA DAHİL"], "material": "Masif Meşe MDF", "desc": "Doğal ahşap aynası ve geniş çekmeceleriyle şifonyer."},
    {"id": 74, "title": "Respiro Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 8000, "originalPrice": 9500, "image": "assets/minegolden_p16_5.webp", "gallery": ["assets/minegolden_p16_5.webp", "assets/minegolden_p16_1.webp", "assets/minegolden_p16_2.webp"], "badges": ["2'Lİ SET"], "material": "Masif Meşe", "desc": "2 adet masif ahşap komodin."},

    {"id": 75, "title": "Asya Modern Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 54000, "originalPrice": 63000, "image": "assets/minegolden_p17_1.webp", "gallery": ["assets/minegolden_p17_1.webp", "assets/minegolden_p17_2.webp", "assets/minegolden_p17_3.webp", "assets/minegolden_p17_4.webp", "assets/minegolden_p17_5.webp", "assets/minegolden_p17_6.webp"], "badges": ["MODERN DİZAYN"], "material": "MDF Gövde & Özel Dokuma Başlık", "desc": "Modern gardırop, sandıklı bazalı karyola, şifonyer ve komodin takımı."},
    {"id": 76, "title": "Asya 6 Kapaklı Gardırop", "category": "bedroom", "subcategory": "wardrobes", "productType": "Solo", "price": 26000, "originalPrice": 30500, "image": "assets/minegolden_p17_2.webp", "gallery": ["assets/minegolden_p17_2.webp", "assets/minegolden_p17_1.webp", "assets/minegolden_p17_6.webp"], "badges": ["FRENLİ SİSTEM"], "material": "MDF Gövde", "desc": "Aynalı orta kapakları ve bol raflı iç yapısıyla gardırop."},
    {"id": 77, "title": "Asya Karyola (Başlıklı)", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 19000, "originalPrice": 22500, "image": "assets/minegolden_p17_3.webp", "gallery": ["assets/minegolden_p17_3.webp", "assets/minegolden_p17_1.webp", "assets/minegolden_p17_5.webp"], "badges": ["BAZALI"], "material": "Dokuma Kumaş & Çelik Baza", "desc": "Yumuşak dokulu kumaş başlığı ve geniş bazasıyla karyola."},
    {"id": 78, "title": "Asya Şifonyer & Aynası", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 14000, "originalPrice": 16500, "image": "assets/minegolden_p17_4.webp", "gallery": ["assets/minegolden_p17_4.webp", "assets/minegolden_p17_1.webp", "assets/minegolden_p17_6.webp"], "badges": ["AYNA DAHİL"], "material": "MDF & Aynalı Panel", "desc": "Modern şifonyer ve makyaj aynası."},
    {"id": 79, "title": "Asya Komodin (2 Adet)", "category": "bedroom", "subcategory": "nightstands", "productType": "Solo", "price": 8200, "originalPrice": 9800, "image": "assets/minegolden_p17_5.webp", "gallery": ["assets/minegolden_p17_5.webp", "assets/minegolden_p17_1.webp", "assets/minegolden_p17_3.webp"], "badges": ["2'Lİ SET"], "material": "MDF & Raylı Çekmece", "desc": "2 adet şık yatak başı komodini."},

    {"id": 80, "title": "Akdeniz Masif Yatak Odası Takımı", "category": "bedroom", "subcategory": "beds", "productType": "Set", "price": 56000, "originalPrice": 65000, "image": "assets/minegolden_p18_1.webp", "gallery": ["assets/minegolden_p18_1.webp", "assets/minegolden_p18_2.webp", "assets/minegolden_p18_3.webp"], "badges": ["MASİF AĞAÇ"], "material": "Fırınlanmış Doğal Masif Ağaç", "desc": "Akdeniz mimarisinden ilham alan doğal ahşap yatak odası takımı."},
    {"id": 81, "title": "Akdeniz Masif Ahşap Karyola", "category": "bedroom", "subcategory": "beds", "productType": "Solo", "price": 20500, "originalPrice": 24000, "image": "assets/minegolden_p18_2.webp", "gallery": ["assets/minegolden_p18_2.webp", "assets/minegolden_p18_1.webp"], "badges": ["MASİF KARYOLA"], "material": "Masif Ağaç Gövde", "desc": "Doğal ahşap dokulu dayanıklı karyola."},
    {"id": 82, "title": "Akdeniz Şifonyer & Komodin Seti", "category": "bedroom", "subcategory": "consoles", "productType": "Solo", "price": 17500, "originalPrice": 20500, "image": "assets/minegolden_p18_3.webp", "gallery": ["assets/minegolden_p18_3.webp", "assets/minegolden_p18_1.webp"], "badges": ["SET OLARAK"], "material": "Masif Ahşap Gövde", "desc": "Masif ahşap şifonyer ve tamamlayıcı komodin seti."}
]

# Guarantee gallery[0] === image for every single product
for p in PRODUCTS_DATA:
    img = p['image']
    gal = [x for x in p['gallery'] if x != img]
    p['gallery'] = [img] + gal

# 1. Update js/app.js and js/detail.js
for target in ['js/app.js', 'js/detail.js']:
    c = open(target, encoding='utf-8').read()
    c = re.sub(r'const PRODUCTS = \[[\s\S]*?\n\];', 'const PRODUCTS = ' + json.dumps(PRODUCTS_DATA, ensure_ascii=False, indent=2) + ';', c)
    open(target, 'w', encoding='utf-8').write(c)
    print(f"Synced {target}")

# 2. Update js/store-service.js
store_c = open('js/store-service.js', encoding='utf-8').read()
store_c = re.sub(
    r'const SEED_PRODUCTS = \[[\s\S]*?\n    \];',
    'const SEED_PRODUCTS = ' + json.dumps(PRODUCTS_DATA, ensure_ascii=False, indent=8) + ';',
    store_c
)
store_c = re.sub(r'const CATALOG_VERSION = "[^"]+";', 'const CATALOG_VERSION = "20260826_FINAL_CORRECT_TITLES_V4";', store_c)
open('js/store-service.js', 'w', encoding='utf-8').write(store_c)
print("Updated js/store-service.js with 20260826_FINAL_CORRECT_TITLES_V4")

# 3. Update SQLite database/mobelmor.db
conn = sqlite3.connect('database/mobelmor.db')
cursor = conn.cursor()
cursor.execute("DELETE FROM products;")
for p in PRODUCTS_DATA:
    cursor.execute("""
        INSERT INTO products (
            id, title, slug, category_slug, subcategory_slug, product_type, price, old_price, rating, reviews_count, main_image, material, description
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        p['id'],
        p['title'],
        p['title'].lower().replace(' ', '-').replace('&', 've'),
        p['category'],
        p.get('subcategory', ''),
        p.get('productType', 'Solo'),
        p['price'],
        p.get('originalPrice', 0),
        p.get('rating', 4.9),
        p.get('reviewsCount', 25),
        p['image'],
        p.get('material', ''),
        p.get('desc', '')
    ))
conn.commit()
conn.close()
print("Updated SQLite database/mobelmor.db")
